apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo-demo
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo-demo
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017